using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;

public class WaveControl : MonoBehaviour
{
    private static WaveControl _instance;
    public static WaveControl Instance
    {
        get
        {
            return _instance;
        }
    }

    [SerializeField, Header("C栏家Α")]
    private int gameMode = 0; // 0: Survive 1: Defence

    [SerializeField, Header("程ji计")]
    private int maxWave = 20;
    private int currentWave = 0;

    [SerializeField, Header("Ci}l")]
    private bool waveStart;

    [SerializeField, Header("Ci┣计q")]
    private List<WaveControlInfo.EnemiesIndex> waves = new List<WaveControlInfo.EnemiesIndex>();

    [SerializeField, Header("┣SO, s腹岸锭")]
    private EnemyScriptObject[] enemyData;

    [SerializeField, Header("┣b初春计q")]
    private List<GameObject> enemyInScene = new List<GameObject>();

    [SerializeField, Header("┣i计jて戈T")]
    private List<WaveControlInfo.BonusInfo> bonusInfo = new List<WaveControlInfo.BonusInfo>();

    private List<Transform> enemySpawnPoint = new List<Transform>();

    [SerializeField, Header("┣家O")]
    private GameObject enemyTemp;

    [SerializeField, Header("UI")]
    private TextMeshProUGUI tmpWaveInfo;

    private bool allClear = false;

    [Header("碑a氦`")]
    public bool isPlayerDead = false;

    private void Awake()
    {
        _instance = this;

        GetAllSpawnPoint();

        allClear = false;
        isPlayerDead = false;
    }
    private void Start()
    {
        UpdateWaveInfo();
        StartCoroutine(StartWave());
    }
    private void Update()
    {
        UpdateWave();

        /*
        if (Input.GetKeyDown(KeyCode.Equals))
        {
            StartCoroutine(StartWave());
        }
        */
    }

    /// <summary>
    /// }li计
    /// </summary>
    /// <returns></returns>
    IEnumerator StartWave()
    {
        yield return new WaitForSeconds(3f);
        waveStart = true;
    }

    private void UpdateWaveInfo()
    {
        tmpWaveInfo.text = "Wave : " + currentWave + " / " + maxWave;
    }


    /// <summary>
    /// ъ飑姚唱涵ネI
    /// </summary>
    private void GetAllSpawnPoint()
    {
        Transform _spg = GameObject.Find("SpawnPointGroup").transform;
        for (int i = 0; i < _spg.childCount; i++)
        {
            enemySpawnPoint.Add(_spg.GetChild(i).transform);
        }
    }

    /// <summary>
    /// ネΘ寄H s腹 wave-index-count
    /// </summary>
    private void SpawnWaveEnemy()
    {
        if (waveStart) return;

        for (int i = 0; i < waves[currentWave].index.Count; i++) // ъindex
        {
            for (int c = 0; c < waves[currentWave].index[i].count; c++) // ъ计q
            {
                int randomPos = (int)Random.Range(0, enemySpawnPoint.Count - 1);
                Vector3 randomOffset = new Vector2(Random.Range(0, 1), Random.Range(0, 1));
                GameObject enemy = Instantiate(enemyTemp, enemySpawnPoint[randomPos].position + randomOffset * 1.5f, Quaternion.identity);
                enemy.GetComponent<EnemyAttribute>().SetEnemyData(enemyData[i]);
                enemy.name = currentWave + "-" + i + "-" + c + "- Enemy";
                enemy.SetActive(true);

                enemyInScene.Add(enemy);
            }
        }

        waveStart = true;
    }

    private bool CheckWaveClear()
    {
        if (enemyInScene.Count == 0 && waveStart)
        {
            waveStart = false;
            return true;
        }
        else
        {
            return false;
        }
    }

    private void UpdateWave()
    {

        if (!CheckWaveClear()) return;

        if (currentWave < maxWave)
        {
            SpawnWaveEnemy();
            currentWave++;
            UpdateWaveInfo();
        }

        if (currentWave == maxWave && !allClear && enemyInScene.Count == 0)
        {
            allClear = true;
            GameMenuControl.Instance.EndGame(true);
        }
    }

    /// <summary>
    /// R埃C恧お焊戤
    /// </summary>
    /// <param name="enemy"></param>
    public void DeleteOnEnemyList(GameObject enemy)
    {
        if (enemyInScene.Contains(enemy))
        {
            enemyInScene.Remove(enemyInScene.Find(x => x.name == enemy.name));
        }
    }

}

namespace WaveControlInfo
{
    [System.Serializable]
    public class EnemiesIndex
    {
        [Header("┣s腹")]
        public List<EnemiesCount> index = new List<EnemiesCount>();
    }

    [System.Serializable]
    public class EnemiesCount
    {
        [Header("┣计q")]
        public int count = 0;
    }

    [System.Serializable]
    public class BonusInfo
    {
        [Header("坎v姒 : 1.00f")]
        public float hpBonus = 1;
        public float damageBonus = 1;
        public float moveBonus = 1;
    }
}


